export const ADD_WIDGET = 'ADD_WIDGET';
export const REMOVE_WIDGET = 'REMOVE_WIDGET';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const GET_FORECAST_BY_QUERY = 'GET_FORECAST_BY_QUERY';
export const PERSIST_STATE = 'PERSIST_STATE';
